{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.129.1229.0 (24.05)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"assetment_bookmaker_powerbi\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "d2fdcfdc-5ccf-43bf-8f17-f107b32617ad",
        "fromColumn": "periodo",
        "fromTable": "assetment_bookmaker_powerbi",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_3a31ffae-6cd8-4e08-b289-22d9f12e68c8"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_179f0a53-9806-457d-9596-5b6b97d25e69",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "12b8bebd-c08c-4dab-913d-383891548a78",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "9c330633-e720-4aca-9231-bb15ae9a4b3f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "c8b6d0d6-cee3-45df-953b-da7625a9a1ed",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "63073b9f-9097-4842-8bbb-9e31f8b2595a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "c624bebc-539b-457e-bf80-8f7c176c04cc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "ce8b4cdd-848c-4669-9a91-8d577ffcc224",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "29772516-9808-4ae4-882a-1b1dff967136",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "3ed92cd3-869a-4f5f-80ae-1650a52bbddf",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "b512cfe6-31f1-44ff-87df-1e281315c7e9",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d7602288-f64b-4367-99d3-3f33e5d8f1bb",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "1b445f8b-3425-4a17-b944-f96d81a3ec42",
                "ordinal": 3
              }
            ],
            "lineageTag": "1d2c709c-1340-4d81-927c-3bb8751d6769"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "ec6975d0-4ff5-42e8-bba9-fa37c80b71e9",
        "partitions": [
          {
            "name": "DateTableTemplate_179f0a53-9806-457d-9596-5b6b97d25e69",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "assetment_bookmaker_powerbi",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "periodo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "3453c585-05cd-4dd4-892e-510d9a1fc331",
            "sourceColumn": "periodo",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_3a31ffae-6cd8-4e08-b289-22d9f12e68c8"
                },
                "isDefault": true,
                "relationship": "d2fdcfdc-5ccf-43bf-8f17-f107b32617ad"
              }
            ]
          },
          {
            "name": "clicks",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "98465409-7e8d-4254-8f0b-18a61de7f62c",
            "sourceColumn": "clicks",
            "summarizeBy": "sum"
          },
          {
            "name": "registrosIN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d9c0fb0e-dea5-46b1-855b-9fde51320f65",
            "sourceColumn": "registrosIN",
            "summarizeBy": "sum"
          },
          {
            "name": "primer_depositoIN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "72060e9c-8606-444d-8573-58eac73a4f6f",
            "sourceColumn": "primer_depositoIN",
            "summarizeBy": "sum"
          },
          {
            "name": "total_depositadoIN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b3e617af-a7da-46c6-938a-550f1e4795a0",
            "sourceColumn": "total_depositadoIN",
            "summarizeBy": "sum"
          },
          {
            "name": "personas_apostaronIN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2d5d2a0a-fd4a-4092-9beb-b8ca8218488d",
            "sourceColumn": "personas_apostaronIN",
            "summarizeBy": "sum"
          },
          {
            "name": "total_apostado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8103897c-1c53-4e67-bcb4-fe801c3e722b",
            "sourceColumn": "total_apostado",
            "summarizeBy": "sum"
          },
          {
            "name": "net_revenueIN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "563eb875-0dcd-4f22-817b-7fe791628fd3",
            "sourceColumn": "net_revenueIN",
            "summarizeBy": "sum"
          },
          {
            "name": "tamaño_apuesta",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "assetment_bookmaker_powerbi[total_apostado] / assetment_bookmaker_powerbi[personas_apostaronIN]",
            "isDataTypeInferred": true,
            "lineageTag": "9f3ed243-09dc-4c1c-b75c-cb4a42733c15",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Tasa nuevos registros",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": "assetment_bookmaker_powerbi[registrosIN] / assetment_bookmaker_powerbi[clicks]",
            "formatString": "0.00%;-0.00%;0.00%",
            "isDataTypeInferred": true,
            "lineageTag": "00f4a5bb-c14d-4fd9-8b5b-bb91e85dadbe",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "b5dc7109-0cd9-4771-acca-ee7523c7030f",
        "measures": [
          {
            "name": "Ingresos Netos",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(assetment_bookmaker_powerbi[net_revenueIN])",
            "lineageTag": "a94b02ea-3132-4e75-8828-688295ceaba6"
          },
          {
            "name": "Jugadores Totales",
            "expression": "SUM(assetment_bookmaker_powerbi[personas_apostaronIN])",
            "formatString": "0",
            "lineageTag": "4fb5f500-c65b-4ebe-ab6a-7646a1c599e0"
          },
          {
            "name": "Apuesta Promedio",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE(SUM(assetment_bookmaker_powerbi[total_apostado]),SUM(assetment_bookmaker_powerbi[personas_apostaronIN]))",
            "lineageTag": "fb411679-5d02-4a3f-a6e5-4e10a0c0ee9b"
          },
          {
            "name": "Tasa conversion",
            "expression": "SUM(assetment_bookmaker_powerbi[primer_depositoIN]) / SUM(assetment_bookmaker_powerbi[registrosIN])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2ea9c7f4-49c4-42d9-9229-3e6ec84272f7"
          },
          {
            "name": "Tasa nuevos usuarios",
            "expression": "SUM(assetment_bookmaker_powerbi[registrosIN]) / SUM(assetment_bookmaker_powerbi[clicks])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "88941e12-46da-4760-ab73-d9224c1ac808"
          },
          {
            "name": "Total Apuestas",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(assetment_bookmaker_powerbi[total_apostado])",
            "lineageTag": "cf4da5cd-c7d6-49b1-91d6-0f48a100c16e"
          },
          {
            "name": "Margen de Ganancias",
            "expression": "SUM(assetment_bookmaker_powerbi[net_revenueIN]) / SUM(assetment_bookmaker_powerbi[total_apostado])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "264cba97-ef1a-4cc0-af1e-35bb5a5543e5"
          },
          {
            "name": "Nuevos usuarios",
            "expression": "SUM(assetment_bookmaker_powerbi[registrosIN])",
            "formatString": "0",
            "lineageTag": "0ba0b330-44b0-4720-9566-b246c8e61310"
          }
        ],
        "partitions": [
          {
            "name": "assetment_bookmaker_powerbi",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\andre\\Documents\\Prueba_tecnica_INLAZE\\assetment_bookmaker_powerbi.csv\"),[Delimiter=\",\", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"periodo\", type date}, {\"clicks\", Int64.Type}, {\"registrosIN\", Int64.Type}, {\"primer_depositoIN\", Int64.Type}, {\"total_depositadoIN\", type number}, {\"personas_apostaronIN\", Int64.Type}, {\"total_apostado\", type number}, {\"net_revenueIN\", type number}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_3a31ffae-6cd8-4e08-b289-22d9f12e68c8",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "756bb98a-c35d-4232-a7a9-d75714ff01a7",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "6d58e002-85a8-45d7-85ea-0d9f6a1794f4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "6d4a5145-eb53-4a14-8ede-204bba2223d0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "1dcaa740-d5e7-444b-9b3a-18b710dfaca8",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "db55e821-4575-4a08-82a2-6f17d11d4dc9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "4e509735-35c1-4b02-b0ff-cbbc8418baa7",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "84f62102-2471-408a-9f64-53a654486540",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "7428509d-8e03-4c0a-8280-9cc4a515daa3",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "2f8168ea-53c5-40ab-8c7f-e4b9fe1358b7",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "8fccbefc-3253-4a51-a952-aebed552aac8",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "6706f0ef-e9bd-4337-ba97-b5102736c12c",
                "ordinal": 3
              }
            ],
            "lineageTag": "0840be64-9352-4790-a2b3-2d0bd5f3d0b9"
          }
        ],
        "isHidden": true,
        "lineageTag": "08f7bbdb-d1d8-42ba-8b49-ff2211f59e4e",
        "partitions": [
          {
            "name": "LocalDateTable_3a31ffae-6cd8-4e08-b289-22d9f12e68c8",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('assetment_bookmaker_powerbi'[periodo])), 1, 1), Date(Year(MAX('assetment_bookmaker_powerbi'[periodo])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}